version: "3.3"
services:
        dbsql:
                image: mysql:8
                env_file: ./.env
                environment:
                        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
                        - MYSQL_DATABASE=$MYSQLDB_DATABASE
                ports:
                        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
                volumes:
                        - ./db:/var/lib/mysql
                        - ./script/:/docker-entrypoint-initdb.d
        app:
                depends_on:
                        - dbsql
                build: ./server
                restart: on-failure
                env_file: ./.env
                ports:
                        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
                environment:
                        SPRING_APPLICATION_JSON: '{
                                "spring.datasource.url" : "jdbc:mysql://dbsql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
                                "spring.datasource.username" : "$MYSQLDB_USER",
                                "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
                                "spring.jpa.hibernate.ddl-auto" : "update",
                                "spring.jpa.hibernate.naming.physical-strategy" : "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
                        }'
                volumes:
                        - .m2:/root/.m2
                stdin_open: true
                tty: true
        frontapp:
                container_name: frontapp
                image: vuefs
                depends_on:
                        - app
                ports:
                        - 80:80
volumes:
  db:
